CREATE TABLE pomodoro (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL,
  duration INTEGER NOT NULL,
  remaining_duration INTEGER NOT NULL,
  status INTEGER NOT NULL,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted BOOLEAN NOT NULL DEFAULT FALSE
);