// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Pomodoro struct {
	ID        string `json:"id"`
	Remaining string `json:"remaining"`
	Status    string `json:"status"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
